Allow using --tarPath without --destination
Currently user has to specify `--destination` argument even if one wants
to generate tarball with resulting image:

  % docker run -v $PWD:/context -v $PWD/out:/out gcr.io/kaniko-project/executor:v0.4.0 --context=/context --tarPath=/out/output.tar
  Error: You must provide --destination, or use --no-push
  Usage:
  ...

This can be worked around by specifying `--destination=nothing`:

  % docker run -v $PWD:/context -v $PWD/out:/out gcr.io/kaniko-project/executor:v0.4.0 --context=/context --tarPath=/out/output.tar --destination=nothing
  INFO[0000] Downloading base image ...

This change removes need for such workaround since `--destination` is
ignored when `--tarPath` is present anyway.